name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - release
      - master
    types: [opened, synchronize, closed]
jobs:
  lambda:
    name: Update Lambda
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --target ./package -r ./pip-requirements.txt
      - name: Zip files
        run: |
          cd package
          zip -r ../lambda.zip .
          cd ..
          zip -r lambda.zip ./lambda_function.py ./aws_utils.py ./slack_utils.py
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_region ${{ secrets.AWS_REGION }}
      - name: Upload to AWS Lambda
        run: |
          aws lambda update-function-code --function-name=bruce-github-actions-test --zip-file=fileb://lambda.zip

